remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#title: [Thaileng Portfolio]
#tagline: [A very short description of your site's purpose, used as subtitle]
#description: [A short description of your site's purpose (e.g. for search engines)]
